MODEL:
  ARCHITECTURE: "RET"
  RET:
    VIDEO_MODE: 'c3d'
    NUM_CLIPS: 64
    JOINT_SPACE_SIZE: 256
    INPUT_TEXT_DIM: 768
    FEATPOOL:
      INPUT_SIZE: 500
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 4
    FEAT2D:
      NAME: "pool"
      POOLING_COUNTS: [15,8,8]
    TEXT_ENCODER:
      NAME: "BERT"
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 9
      NUM_STACK_LAYERS: 4
    LOSS:
      MIN_IOU: 0.5
      MAX_IOU: 1.0
      NUM_POSTIVE_VIDEO_PROPOSAL: 1
      NEGATIVE_VIDEO_IOU: 0.5
      SENT_REMOVAL_IOU: 0.5
      TAU_VIDEO: 0.1
      TAU_SENT: 0.1
      MARGIN: 0.3
      CONTRASTIVE_WEIGHT: 0.1
OUTPUT_DIR: "./activity_layer/6"
DATASETS:
  NAME: "activitynet"
  TRAIN: ("activitynet_train", )
  TEST: ("activitynet_test",)
INPUT:
  NUM_PRE_CLIPS: 256
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  LR: 0.0008
  BATCH_SIZE: 12
  MILESTONES: (7, 15)
  MAX_EPOCH: 15
  TEST_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  RESUME: False
  RESUME_EPOCH: 7
  FREEZE_BERT: 4
  ONLY_IOU: 6
  SKIP_TEST: 1
  USE_LRTNET: True
  MASK_MODE: 'both'     # no  ret   sparse  both
  SPARSE_WEIGHT: 10.0
  ATT_MODE: 'all'     # all  v trans
  D_DOUBLE: True
  ATT_SOFTMAX: True
  ATT_DROPOUT: None
  TRANS_LAYER: 6
  N_HEAD: 8
  GAMMA: 0.98
  LOSS_RATIO: 0.15
TEST:
  NMS_THRESH: 0.5
  BATCH_SIZE: 12
  CONTRASTIVE_SCORE_POW: 0.5
