MODEL:
  ARCHITECTURE: "RET"
  RET:
    VIDEO_MODE: 'i3d'
    NUM_CLIPS: 64
    JOINT_SPACE_SIZE: 256
    INPUT_TEXT_DIM: 768
    FEATPOOL:
      INPUT_SIZE: 1024
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 2
    FEAT2D:
      NAME: "pool"
      POOLING_COUNTS: [15, 8, 8]
    TEXT_ENCODER:
      NAME: "BERT"
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 17
      NUM_STACK_LAYERS: 2
    LOSS:
      MIN_IOU: 0.5
      MAX_IOU: 1.0
      NUM_POSTIVE_VIDEO_PROPOSAL: 1
      NEGATIVE_VIDEO_IOU: 0.5
      SENT_REMOVAL_IOU: 0.5
      TAU_VIDEO: 0.1
      TAU_SENT: 0.1
      MARGIN: 0.4
      CONTRASTIVE_WEIGHT: 0.05
OUTPUT_DIR: './sta_new/decay/99'
DATASETS:
  NAME: "charades"
  TRAIN: ("charades_train", )
  TEST: ("charades_test",)
INPUT:
  NUM_PRE_CLIPS: 128
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  LR: 0.0001
  BATCH_SIZE: 12
  MILESTONES: (8, 13)
  MAX_EPOCH: 25
  TEST_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  RESUME: False
  RESUME_EPOCH: 18
  FREEZE_BERT: 60
  ONLY_IOU: 7
  SKIP_TEST: 1
  USE_LRTNET: True
  MASK_MODE: 'both'     # no  ret   sparse  both
  SPARSE_WEIGHT: 10.0
  ATT_MODE: 'v'     # all  v
  D_DOUBLE: True
  ATT_SOFTMAX: True
  ATT_DROPOUT: None
  TRANS_LAYER: 2
  N_HEAD: 8
  GAMMA: 0.99
  LOSS_RATIO: 0.00
TEST:
  NMS_THRESH: 0.5
  BATCH_SIZE: 12
  CONTRASTIVE_SCORE_POW: 0.5
