MODEL:
  ARCHITECTURE: "RET"
  RET:
    NUM_CLIPS: 128
    JOINT_SPACE_SIZE: 256
    INPUT_TEXT_DIM: 768
    FEATPOOL:
      INPUT_SIZE: 500
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 4
    FEAT2D:
      NAME: "pool"
      POOLING_COUNTS: [15,8,8,8]
    TEXT_ENCODER:
      NAME: 'BERT'
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 5
      NUM_STACK_LAYERS: 3
    LOSS:
      MIN_IOU: 0.3
      MAX_IOU: 0.7
      NUM_POSTIVE_VIDEO_PROPOSAL: 3
      NEGATIVE_VIDEO_IOU: 0.5
      SENT_REMOVAL_IOU: 0.5
      TAU_VIDEO: 0.1
      TAU_SENT: 0.1
      MARGIN: 0.1
      CONTRASTIVE_WEIGHT: 0.1
DATASETS:
  NAME: "tacos"
  TRAIN: ("tacos_train",)
  TEST: ("tacos_test",)
INPUT:
  NUM_PRE_CLIPS: 512
DATALOADER:
  NUM_WORKERS: 0
OUTPUT_DIR: ./results_tacos/results_1028/text_new_query/half_only_4
SOLVER:
  LR: 0.0015
  BATCH_SIZE: 12
  MILESTONES: (130, 190)
  MAX_EPOCH: 250
  TEST_PERIOD: 1
  CHECKPOINT_PERIOD: 10
  RESUME: False
  RESUME_EPOCH: 111
  FREEZE_BERT: 400
  ONLY_IOU: 100
  SKIP_TEST: 0
  USE_LRTNET: True
  MASK_MODE: 'both'     # no  ret   sparse  both
  SPARSE_WEIGHT: 20.0
  ATT_MODE: 'all'     # all  v
  D_DOUBLE: True
  ATT_SOFTMAX: True   # False
  ATT_DROPOUT: 0.1
  TRANS_LAYER: 1
  N_HEAD: 8
  GAMMA: 0.99
TEST:
  NMS_THRESH: 0.4
  BATCH_SIZE: 8
  CONTRASTIVE_SCORE_POW: 0.3

